
---
title: Unit verification
author: Osman Alsheghri 
---

## The unit conversion functions
``` {python}
M_co2   = 44.01                 # g/mol
M_h2co3 = 62.03                 # g/mol
M_co3   = 60.01                 # g/mol
M_hco3  = 61.02                 # g/mol
M_oh    = 17.01                 # g/mol
def gpm3_to_molpm3(c, M):
    return c / M

def molpm3_to_gpm3(c, M):
    return c * M

```

Lets make a simple test:
``` {python}
c_oh = 10   #g/m3
gpm3_to_molpm3(c_oh,M_oh)

```
We get the expected result. 

``` {python}
c_h2co3 = 0.1  # mol/m3
molpm3_to_gpm3(c_h2co3,M_h2co3)
```
We get the expected result. 


## Units of concentrations:
``` {python}
# ccg     = ncg    / vol_gas 
# c_co2   = n_co2  / vol_liq
# c_TOTC  = n_TOTC / vol_liq 
```
Since the n is in moles and the volume is in $m^3$ then the units of the concetrations
are $mol/m^3$


## Output from speciation function

``` {python}
# for i in range(nc):
#     res = sm.spec2_matrix(c_TOTC[i], K_hco3, K_co3, KW, ex_oh)
#     c_h2co3[i] = res['c_h2co3']
#     c_hco3[i]  = res['c_hco3']
#     c_co3[i]   = res['c_co3']
#     c_oh[i]    = res['c_oh']
#     c_h[i]     = res['c_h']
#     pH[i]      = res['pH']

```
Since we expect that the speciation function output is in $mol/m^3$ then this would be consistent 
with the other units in the model. 


## The Kga calculation
``` {python}
#| eval: false
#| echo: true
#| comment: "This code is shown for unit verification only - not executed"
  if type(Kga) is str and Kga.lower() == 'onda':
      # Hard-wired constants
      g      = 9.81                   # m/s^2   
      Dg     = 1.16E-5                # m^2 / s    
      Dliq   = 1.89E-9                # m^2/ s                                 
      sigm_c = 0.75                   # unit is not given here
      sigm_l = 0.0073                 # also not here
      R      = 0.083144               # (L bar / K-mol)
      mw_g   = 28.97                  #  (g/mol)
      dp     = 6 * (1 - por_g) / ssa  # characteristic packing length

      # empirical correlation for particle diameter
      if dp < 15:
          dp_emp = 2.0
      else:
          dp_emp = 5.23

      # temp in kelvin
      TK = temp + 273.15

      dens_g = pres * mw_g / (R * TK)     # bar * g/mol / (L*bar/(K*mol) * K)  = g/L = kg/m3  
      visc_g = 9.1E-8 * TK - 1.16E-5      # no units given
      visc_l = -2.55E-5 * TK + 8.51E-3    # same here 

      # Dimensionless numbers 
      Re = dens_l * v_l / (ssa * visc_l)                # reynold
      Fr = v_l * v_l * ssa / g                          # Froude number
      We = v_l * v_l * dens_l / (sigm_l * ssa)          # Weber number
      
      # some effective area for mass transfer? 
      ae = ssa * (1.0-2.71828**(-1.45 * (sigm_c / sigm_l)**0.75 *
                              Re**0.1 * Fr**-0.05 * We**0.2))    # m^2/m^3
     
      #gas phase resistance
      kg = dp_emp * (v_g * dens_g / (ssa * visc_g))**0.7 \
          * (visc_g / (dens_g * Dg))**(1 / 3) * (ssa * dp)**-2 * ssa * Dg
      # (m/s * kg/m^3 / (m^2/m^3 * kg/(m*s)))^0.7 * (kg/(m*s) /(kg/m^3 * m^2/s))^(1/3) * (m^2/m^3 * m)^-2 * m^2/m^3 * m^2/s = m/s ? Mathcad
      
      #liquid phase resistance
      kl = 0.0051 * (v_l * dens_l / (ae * visc_l))**(2/3) * (visc_l / (dens_l * Dliq))**(-0.5) * (ssa * dp)**0.4 * (dens_l / (visc_l * g))**(-1/3) 
    # (m/s * kg/m^3 / (m^2/m^3 * kg/(m*s)))^(2/3) * (kg/(m*s) / (kg/m^3 * m^2/s))^(-0.5) * (m^2/m^3 * m)^0.4 * (kg/m^3 / (kg/(m*s)*m/s^2)) ^(-1/3) = m/s 

     
      kh  = henry[0] * np.exp(henry[1] * (1/TK - 1/298.15))    # mol/kg-bar as liq:gas   # vant hoff equation for calculating new henry constant
      kh  = kh * dens_l / 1000                                 # mol/L-bar
      Kaw = 1 / (kh * R * TK) # mol/L-bar * L*bar/K-mol * K = dimensionless                                                                                                                                        

      Daw = Kaw                                                # dimensionless
      c_co2i = ccg / Kaw 
      if enh_method is not None:
          E = em.enh_fac(
              c_oh   = c_oh,
              c_co2  = c_co2i,
              k      = k3,
              K      = K4,
              kl     = kl,
              method = enh_method
              )
      else:
          E = 1

      Rtot = 1 / (kg * ae) + Daw / (kl * ae * E) + Daw / (k1 * por_l) # reference p181 in Seader et al book (resistance in serie two film)
      # 1/(m/s * m^2/m^3) + 1/(m/s * m^2/m^3) + 1/(1/s * m^3/m^3) 
      # 1/s^-1 + 1/s^-1 + 1/s^-1 = s  
      Kga  = 1 / Rtot     # 1/s 
```


## Reservoir ODEs
``` {python}
#| eval: false
#| echo: true
#| comment: "This code is shown for unit verification only - not executed"
dmcr_co2  = (c_co2[oi] - cr_co2) * abs(v_l) - rxnr_co2 * v_res 
# mol/m3 * m/s - mol/m3-s * m3/m2 = mol/m2-s - mol/m2-s  but since A = 1 m^2  we get mol/s
dmcr_TOTC = (c_TOTC[oi] - cr_TOTC)*abs(v_l) + rxnr_TOTC * v_res
# the same here
```



## the reaction rates
``` {python}
#| eval: false
#| echo: true
#| comment: "This code is shown for unit verification only - not executed"
r1 = k1 * c_co2 - k2 * c_h2co3          # 1/s * mol/m3 - 1/s * mol/m3 = mol/m^3-s
r2 = k3 * c_co2 * c_oh - k4 * c_hco3  # m3/mol-s * mol/m3 * mol/m3 - 1/s * mol/mo3 = mol/m^3-s
```


## The mass transfer term
``` {python}
#| eval: false
#| echo: true
#| comment: "This code is shown for unit verification only - not executed"

g2l = Kga * vol_tot * (ccg - c_co2 * Daw) 
#     1/s * m3 * mol/m3 = mol/s 
```

## The PDEs
``` {python}
#| eval: false
#| echo: true
#| comment: "This code is shown for unit verification only - not executed"
advec_gas = - v_g * np.diff(cvec_gas) # m/s * mol/m3 = mol/m2-s but since the area = 1m2 this becomes mol/s
dmg       = advec_gas - g2l           # mol/s - mol/s = mol/s       



advec_co2 = - v_l_eff * np.diff(cvec_co2)  # m/s * mol/m3 * 1 m2 = mol/s 
dm_co2 = advec_co2 + g2l + rxn_co2 * vol_liq # mol/s + mol/s - mol/m3-s * m3 = mol/s

advec_TOTC = - v_l_eff * np.diff(cvec_TOTC) # the same as for co2
dm_TOTC    = advec_TOTC  + rxn_TOTC * vol_liq
```



## Equilibrium constants in the tfmod

``` {python}
#| eval: false
#| echo: true
#| comment: "This code is shown for unit verification only - not executed"
# Temperature dependent constants
KW        = 10**(-4.2195 - 2915.16/TK)  * 10**6 
# units are in  mol^2/L^2


rho_water = 1000 * (1 - ((temp + 288.9414) / (508929.2 * (temp + 68.12963))) * (temp - 3.9863)**2) 
# the units are in kg/m3
K2  = np.exp(-12092.1/TK -36.786 * np.log(TK) + 235.482) * rho_water
# mol/m3


K4        = K2/KW  
```
here comes the mistake: 
K2 has units of $mol/m^3$ but KW has units of $mol^2/L^2$ so we actually need to correct this.
Then the equation becomes
$$K_4 = K_2 / (K_W * 10^6) $$


$K_W$ still needs to be in $mol^2/L^2$ because of the specaition model.  
All the equlibrium constants passed to the speciation model needs to be in $mol/L$ units.
And all the constants used in the main model and the enhancement factor model needs to be in $mol/m^3$ 


